deepin-license: get dkms sourece version from file.
Change-Id: I48fc1a9afb8b2eae08e5ae3f91ed6a9d583aa4d1

diff --git a/deepin-license/debian/deepin-license-dkms.postinst b/deepin-license/debian/deepin-license-dkms.postinst
--- a/deepin-license/debian/deepin-license-dkms.postinst
+++ b/deepin-license/debian/deepin-license-dkms.postinst
@@ -9,20 +9,21 @@ set -e
 NAME=deepin_license
 PACKAGE_NAME=$NAME-dkms
 DEB_NAME=$(echo $PACKAGE_NAME | sed 's,_,-,')
-CVERSION=`dpkg-query -W -f='${Version}' $DEB_NAME | awk -F "-" '{print $1}' | cut -d\: -f2`
+#CVERSION=`dpkg-query -W -f='${Version}' $DEB_NAME | awk -F "-" '{print $1}' | cut -d\: -f2`
+CVERSION=`cat /usr/share/$DEB_NAME/version`
 ARCH=`dpkg --print-architecture`
 
 dkms_configure () {
-	for POSTINST in /usr/lib/dkms/common.postinst "/usr/share/$PACKAGE_NAME/postinst"; do
+	for POSTINST in /usr/lib/dkms/common.postinst "/usr/share/$DEB_NAME/postinst"; do
 		if [ -f "$POSTINST" ]; then
-			"$POSTINST" "$NAME" "$CVERSION" "/usr/share/$PACKAGE_NAME" "$ARCH" "$2"
+			"$POSTINST" "$NAME" "$CVERSION" "/usr/share/$DEB_NAME" "$ARCH" "$2"
 			return $?
 		fi
 		echo "WARNING: $POSTINST does not exist." >&2
 	done
-	echo "ERROR: DKMS version is too old and $PACKAGE_NAME was not" >&2
+	echo "ERROR: DKMS version is too old and $DEB_NAME was not" >&2
 	echo "built with legacy DKMS support." >&2
-	echo "You must either rebuild $PACKAGE_NAME with legacy postinst" >&2
+	echo "You must either rebuild $DEB_NAME with legacy postinst" >&2
 	echo "support or upgrade DKMS to a more current version." >&2
 	return 1
 }
